#! /usr/bin/sh


TARGET_BRANCH="master"
CMD="cd '%' && git stash save && git reset --hard &&  \
git fetch --prune && git checkout -q $TARGET_BRANCH &&  \
git pull --rebase"

find . -maxdepth 1 -type d -print0 | xargs -0 -I% -P$(nproc) -n1 bash -c "$CMD"
